In [50]:
import pytrends
import pandas as pd
from pytrends.request import TrendReq
# from pytrends.request import g
import altair as alt

In [97]:
pytrend = TrendReq(hl='india')

### Rana Daggubati

In [98]:
pytrend.build_payload(kw_list=["Rana Daggubati"])

In [99]:
pytrend.suggestions("Rana")

[{'mid': '/m/0dhzn5', 'title': 'Kangana Ranaut', 'type': 'Indian actress'},
 {'mid': '/m/09ggjsc', 'title': 'Rana Daggubati', 'type': 'Indian film actor'},
 {'mid': '/m/047rw47',
  'title': 'Andrea Ranocchia',
  'type': 'Italian footballer'},
 {'mid': '/m/026hvjz', 'title': 'Gonzalo Jara', 'type': 'Chilean footballer'},
 {'mid': '/m/04c636',
  'title': 'Mithun Chakraborty',
  'type': 'Former Member of Parliament, Rajya Sabha'}]

In [38]:
relatedDF=pytrend.related_topics()

In [100]:
relatedqueriesDF=pytrend.related_queries()

In [101]:
relatedqueriesDF['/m/09ggjsc']['rising']

KeyError: '/m/09ggjsc'

In [42]:
relatedqueriesDF['/m/09ggjsc']['top']

                    query  value
0                    rana    100
1               daggubati     39
2          rana daggubati     39
3              rana movie      9
4            prabhas rana      7
5                 prabhas      7
6                bahubali      4
7           bahubali rana      4
8             rana movies      4
9                rana age      4
10            rana height      3
11                anushka      3
12            rana photos      3
13              rana wife      3
14     rana daggubati age      2
15            rana trisha      2
16                 trisha      2
17            rana images      2
18             rana actor      2
19  rana daggubati height      2
20             rana songs      2
21         anushka shetty      2
22    rana daggubati wife      2
23  rana daggubati movies      2
24               samantha      2

In [102]:
relatedDF['/m/09ggjsc']['rising']

,value,formattedValue,link,topic_mid,topic_title,topic_type
0,103100,Breakout,/trends/explore?q=/g/11c5bj9tww&date=today+5-y,/g/11c5bj9tww,Nene Raju Nene Mantri,2017 film
1,73050,Breakout,/trends/explore?q=/g/11d_29s9ch&date=today+5-y,/g/11d_29s9ch,No.1 Yaari With Rana,Topic
2,40500,Breakout,/trends/explore?q=/g/11b7fhbfz1&date=today+5-y,/g/11b7fhbfz1,Vijay Deverakonda,Indian film actor
3,27350,Breakout,/trends/explore?q=/m/012smw4g&date=today+5-y,/m/012smw4g,Housefull,Film series
4,27250,Breakout,/trends/explore?q=/g/11c2p5734j&date=today+5-y,/g/11c2p5734j,Tujhyat Jeev Rangala,Television film
5,25100,Breakout,/trends/explore?q=/m/0jwjtvb&date=today+5-y,/m/0jwjtvb,Keerthy Suresh,Indian film actress
6,24600,Breakout,/trends/explore?q=/m/0x10ctg&date=today+5-y,/m/0x10ctg,Sri Divya,Indian film actress
7,24000,Breakout,/trends/explore?q=/m/076w0yj&date=today+5-y,/m/076w0yj,Housefull,2010 film
8,23350,Breakout,/trends/explore?q=/m/02w55q&date=today+5-y,/m/02w55q,Bajaj Auto,Company
9,18800,Breakout,/trends/explore?q=/g/11hbvt5ydf&date=today+5-y,/g/11hbvt5ydf,Housefull 4,2019 film
10,18750,Breakout,/trends/explore?q=/m/010x7s0t&date=today+5-y,/m/010x7s0t,Sri Reddy,Indian actress
11,17250,Breakout,/trends/explore?q=/m/013dc2by&date=today+5-y,/m/013dc2by,Sai Pallavi,Indian film actress
12,17250,Breakout,/trends/explore?q=/m/01_2n&date=today+5-y,/m/01_2n,Coronation Street,British television programme
13,9600,Breakout,/trends/explore?q=/m/0h27n6y&date=today+5-y,/m/0h27n6y,Dulquer Salmaan,Indian film actor
14,9550,Breakout,/trends/explore?q=/g/11bxdtnmw6&date=today+5-y,/g/11bxdtnmw6,Viu,Streaming media
15,9450,Breakout,/trends/explore?q=/m/09w2qd&date=today+5-y,/m/09w2qd,Koffee with Karan,Indian talk show
16,4650,"+4,650%",/trends/explore?q=/g/11cllnm004&date=today+5-y,/g/11cllnm004,The Ghazi Attack,2017 film
17,2400,"+2,400%",/trends/explore?q=/g/11b824glqh&date=today+5-y,/g/11b824glqh,Baahubali 2: The Conclusion,2017 film
18,1450,"+1,450%",/trends/explore?q=/m/0nbh0h1&date=today+5-y,/m/0nbh0h1,Age,Topic
19,750,+750%,/trends/explore?q=/m/026dkrk&date=today+5-y,/m/026dkrk,Bigg Boss,Indian television show
20,600,+600%,/trends/explore?q=/m/0jzr9sn&date=today+5-y,/m/0jzr9sn,Rakul Preet Singh,Indian film actress
21,500,+500%,/trends/explore?q=/m/01crvy&date=today+5-y,/m/01crvy,Foot,Unit
22,250,+250%,/trends/explore?q=/m/025rz_f&date=today+5-y,/m/025rz_f,Wife,Topic
23,250,+250%,/trends/explore?q=/m/0807ht1&date=today+5-y,/m/0807ht1,Samantha Akkineni,Indian actress
24,190,+190%,/trends/explore?q=/m/03g_263&date=today+5-y,/m/03g_263,Kajal Aggarwal,Indian film actress

In [103]:
relatedDF['/m/09ggjsc']['top']

,value,formattedValue,hasData,link,topic_mid,topic_title,topic_type
0,100,100,True,/trends/explore?q=/m/0cmn9c&date=today+5-y,/m/0cmn9c,Prabhas,Indian actor
1,78,78,True,/trends/explore?q=/g/11bw1xrcfp&date=today+5-y,/g/11bw1xrcfp,Baahubali,Film series
2,77,77,True,/trends/explore?q=/m/0pmh01t&date=today+5-y,/m/0pmh01t,Baahubali: The Beginning,2015 film
3,52,52,True,/trends/explore?q=/m/01jtb2&date=today+5-y,/m/01jtb2,Height,Topic
4,52,52,True,/trends/explore?q=/m/02hrh1q&date=today+5-y,/m/02hrh1q,Actor,Occupation
5,50,50,True,/trends/explore?q=/m/03nny6&date=today+5-y,/m/03nny6,Human height,Topic
6,45,45,True,/trends/explore?q=/m/09s02&date=today+5-y,/m/09s02,Telugu language,Spoken language
7,39,39,True,/trends/explore?q=/m/0nbh0h1&date=today+5-y,/m/0nbh0h1,Age,Topic
8,39,39,True,/trends/explore?q=/m/025rz_f&date=today+5-y,/m/025rz_f,Wife,Topic
9,36,36,True,/trends/explore?q=/m/0gxv6n&date=today+5-y,/m/0gxv6n,Anushka Shetty,Indian film actress
10,31,31,True,/trends/explore?q=/g/11b824glqh&date=today+5-y,/g/11b824glqh,Baahubali 2: The Conclusion,2017 film
11,30,30,True,/trends/explore?q=/m/05vzql&date=today+5-y,/m/05vzql,Trisha Krishnan,Actress
12,27,27,True,/trends/explore?q=/m/05yhh7&date=today+5-y,/m/05yhh7,Daggubati Venkatesh,Actor
13,25,25,True,/trends/explore?q=/m/01crvy&date=today+5-y,/m/01crvy,Foot,Unit
14,23,23,True,/trends/explore?q=/m/0807ht1&date=today+5-y,/m/0807ht1,Samantha Akkineni,Indian actress
15,23,23,True,/trends/explore?q=/m/03c72bb&date=today+5-y,/m/03c72bb,Ram Charan,Indian film actor
16,22,22,True,/trends/explore?q=/m/02cqmh&date=today+5-y,/m/02cqmh,Telugu cinema,Topic
17,22,22,True,/trends/explore?q=/m/0bj640&date=today+5-y,/m/0bj640,Allu Arjun,Indian film actor
18,21,21,True,/trends/explore?q=/m/03g_263&date=today+5-y,/m/03g_263,Kajal Aggarwal,Indian film actress
19,18,18,True,/trends/explore?q=/m/07t5b3&date=today+5-y,/m/07t5b3,Mahesh Babu,Indian film actor
20,15,15,True,/trends/explore?q=/g/11c5bj9tww&date=today+5-y,/g/11c5bj9tww,Nene Raju Nene Mantri,2017 film
21,11,11,True,/trends/explore?q=/g/11d_29s9ch&date=today+5-y,/g/11d_29s9ch,No.1 Yaari With Rana,Topic
22,10,10,True,/trends/explore?q=/g/11cllnm004&date=today+5-y,/g/11cllnm004,The Ghazi Attack,2017 film
23,9,9,True,/trends/explore?q=/m/0jzr9sn&date=today+5-y,/m/0jzr9sn,Rakul Preet Singh,Indian film actress
24,6,6,True,/trends/explore?q=/g/11b7fhbfz1&date=today+5-y,/g/11b7fhbfz1,Vijay Deverakonda,Indian film actor

In [112]:
interest_by_regionDF=pytrend.interest_by_region()

In [104]:
interest_by_timeDF=pytrend.interest_over_time()

In [115]:
chart=alt.Chart(interest_by_regionDF.sort_values(by="Rana Daggubati",ascending=False).reset_index())

In [116]:
chart.mark_line().encode(alt.X("geoName"),alt.Y("Rana Daggubati",title="Freq of search"))

alt.Chart(...)

In [109]:
interest_by_timeDF1=interest_by_timeDF.reset_index()
time_chart=alt.Chart(interest_by_timeDF1,width=1000)

In [111]:
interest_by_timeDF1

          date  Rana Daggubati isPartial
0   2015-10-18              10     False
1   2015-10-25              11     False
2   2015-11-01               8     False
3   2015-11-08               7     False
4   2015-11-15               4     False
..         ...             ...       ...
256 2020-09-13               6     False
257 2020-09-20               5     False
258 2020-09-27               5     False
259 2020-10-04               5     False
260 2020-10-11               4      True

[261 rows x 3 columns]

In [110]:
interest_by_timeDF1
time_chart.mark_line().encode(alt.X('date'),alt.Y('/m/09ggjsc',title='Freq of search')).interactive()

ValueError: /m/09ggjsc encoding field is specified without a type; the type cannot be inferred because it does not match any column in the data.

alt.Chart(...)

### Rakul Preet Singh

### Comparing Digital presence of the Actors

In [3]:
kw_list =["Rana Daggubati","Rakul Preet Singh"]
pytrend.build_payload(kw_list=kw_list)

In [20]:
# pytrend.related_topics()
pytrend.results

In [21]:
interest_over_time_df = pytrend.interest_over_time()

In [22]:
interest_over_time_df

            /m/09ggjsc isPartial
date
2015-10-18          21     False
2015-10-25          22     False
2015-11-01          21     False
2015-11-08          21     False
2015-11-15          16     False
...                ...       ...
2020-09-13           9     False
2020-09-20          10     False
2020-09-27           9     False
2020-10-04           9     False
2020-10-11           9      True

[261 rows x 2 columns]

In [23]:
interest_by_region_df = pytrend.interest_by_region()
interest_by_region_df.sum()

/m/09ggjsc    677
dtype: int64

In [7]:
interest_by_region_df

Rana     3161
Rakul     239
dtype: int64